import { Outfit } from "next/font/google";
import "./globals.css";
// import "./index.css"
import Header from "./_components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "AI Interviewer Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className} >
        <Header />
          <div>
            {children}
          </div>
      </body>
    </html>
  );
}
